// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="detectFaces_detectFaces,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a50ti-csg324-1L,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.541750,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=246,HLS_SYN_DSP=0,HLS_SYN_FF=63306,HLS_SYN_LUT=91542,HLS_VERSION=2023_2}" *)

module detectFaces (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        inData_address0,
        inData_ce0,
        inData_q0,
        result_x_address0,
        result_x_ce0,
        result_x_we0,
        result_x_d0,
        result_y_address0,
        result_y_ce0,
        result_y_we0,
        result_y_d0,
        result_w_address0,
        result_w_ce0,
        result_w_we0,
        result_w_d0,
        result_h_address0,
        result_h_ce0,
        result_h_we0,
        result_h_d0,
        result_size,
        result_size_ap_vld
);

parameter    ap_ST_fsm_state1 = 58'd1;
parameter    ap_ST_fsm_state2 = 58'd2;
parameter    ap_ST_fsm_state3 = 58'd4;
parameter    ap_ST_fsm_state4 = 58'd8;
parameter    ap_ST_fsm_state5 = 58'd16;
parameter    ap_ST_fsm_state6 = 58'd32;
parameter    ap_ST_fsm_state7 = 58'd64;
parameter    ap_ST_fsm_state8 = 58'd128;
parameter    ap_ST_fsm_state9 = 58'd256;
parameter    ap_ST_fsm_state10 = 58'd512;
parameter    ap_ST_fsm_state11 = 58'd1024;
parameter    ap_ST_fsm_state12 = 58'd2048;
parameter    ap_ST_fsm_state13 = 58'd4096;
parameter    ap_ST_fsm_state14 = 58'd8192;
parameter    ap_ST_fsm_state15 = 58'd16384;
parameter    ap_ST_fsm_state16 = 58'd32768;
parameter    ap_ST_fsm_state17 = 58'd65536;
parameter    ap_ST_fsm_state18 = 58'd131072;
parameter    ap_ST_fsm_state19 = 58'd262144;
parameter    ap_ST_fsm_state20 = 58'd524288;
parameter    ap_ST_fsm_state21 = 58'd1048576;
parameter    ap_ST_fsm_state22 = 58'd2097152;
parameter    ap_ST_fsm_state23 = 58'd4194304;
parameter    ap_ST_fsm_state24 = 58'd8388608;
parameter    ap_ST_fsm_state25 = 58'd16777216;
parameter    ap_ST_fsm_state26 = 58'd33554432;
parameter    ap_ST_fsm_state27 = 58'd67108864;
parameter    ap_ST_fsm_state28 = 58'd134217728;
parameter    ap_ST_fsm_state29 = 58'd268435456;
parameter    ap_ST_fsm_state30 = 58'd536870912;
parameter    ap_ST_fsm_state31 = 58'd1073741824;
parameter    ap_ST_fsm_state32 = 58'd2147483648;
parameter    ap_ST_fsm_state33 = 58'd4294967296;
parameter    ap_ST_fsm_state34 = 58'd8589934592;
parameter    ap_ST_fsm_state35 = 58'd17179869184;
parameter    ap_ST_fsm_state36 = 58'd34359738368;
parameter    ap_ST_fsm_state37 = 58'd68719476736;
parameter    ap_ST_fsm_state38 = 58'd137438953472;
parameter    ap_ST_fsm_state39 = 58'd274877906944;
parameter    ap_ST_fsm_state40 = 58'd549755813888;
parameter    ap_ST_fsm_state41 = 58'd1099511627776;
parameter    ap_ST_fsm_state42 = 58'd2199023255552;
parameter    ap_ST_fsm_state43 = 58'd4398046511104;
parameter    ap_ST_fsm_state44 = 58'd8796093022208;
parameter    ap_ST_fsm_state45 = 58'd17592186044416;
parameter    ap_ST_fsm_state46 = 58'd35184372088832;
parameter    ap_ST_fsm_state47 = 58'd70368744177664;
parameter    ap_ST_fsm_state48 = 58'd140737488355328;
parameter    ap_ST_fsm_state49 = 58'd281474976710656;
parameter    ap_ST_fsm_state50 = 58'd562949953421312;
parameter    ap_ST_fsm_state51 = 58'd1125899906842624;
parameter    ap_ST_fsm_state52 = 58'd2251799813685248;
parameter    ap_ST_fsm_state53 = 58'd4503599627370496;
parameter    ap_ST_fsm_state54 = 58'd9007199254740992;
parameter    ap_ST_fsm_state55 = 58'd18014398509481984;
parameter    ap_ST_fsm_state56 = 58'd36028797018963968;
parameter    ap_ST_fsm_state57 = 58'd72057594037927936;
parameter    ap_ST_fsm_state58 = 58'd144115188075855872;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] inData_address0;
output   inData_ce0;
input  [7:0] inData_q0;
output  [6:0] result_x_address0;
output   result_x_ce0;
output   result_x_we0;
output  [31:0] result_x_d0;
output  [6:0] result_y_address0;
output   result_y_ce0;
output   result_y_we0;
output  [31:0] result_y_d0;
output  [6:0] result_w_address0;
output   result_w_ce0;
output   result_w_we0;
output  [31:0] result_w_d0;
output  [6:0] result_h_address0;
output   result_h_ce0;
output   result_h_we0;
output  [31:0] result_h_d0;
output  [31:0] result_size;
output   result_size_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[6:0] result_x_address0;
reg result_x_ce0;
reg result_x_we0;
reg[31:0] result_x_d0;
reg[6:0] result_y_address0;
reg result_y_ce0;
reg result_y_we0;
reg[31:0] result_y_d0;
reg[6:0] result_w_address0;
reg result_w_ce0;
reg result_w_we0;
reg[31:0] result_w_d0;
reg[6:0] result_h_address0;
reg result_h_ce0;
reg result_h_we0;
reg[31:0] result_h_d0;
reg result_size_ap_vld;

(* fsm_encoding = "none" *) reg   [57:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] counter;
reg   [16:0] Data_address0;
reg    Data_ce0;
reg    Data_we0;
wire   [7:0] Data_q0;
wire   [31:0] grp_fu_359_p2;
reg   [31:0] reg_393;
wire    ap_CS_fsm_state23;
wire    ap_CS_fsm_state41;
wire   [0:0] icmp_ln2849_fu_411_p2;
reg   [0:0] icmp_ln2849_reg_1046;
wire   [16:0] add_ln2851_fu_433_p2;
reg   [16:0] add_ln2851_reg_1050;
wire   [0:0] icmp_ln2854_fu_452_p2;
reg   [0:0] icmp_ln2854_reg_1055;
reg   [31:0] factor_2_reg_1073;
wire    ap_CS_fsm_state3;
wire   [31:0] grp_fu_365_p2;
reg   [31:0] dc_2_reg_1079;
wire    ap_CS_fsm_state18;
wire   [31:0] grp_fu_370_p2;
reg   [31:0] dc_3_reg_1085;
reg   [31:0] res_size_Scale_0_load_reg_1091;
wire    ap_CS_fsm_state20;
wire   [22:0] trunc_ln2885_1_fu_530_p1;
reg   [22:0] trunc_ln2885_1_reg_1096;
reg   [0:0] xs_sign_2_reg_1104;
wire   [0:0] tmp_12_fu_596_p3;
reg   [0:0] tmp_12_reg_1110;
reg   [31:0] tmp_31_reg_1115;
reg   [31:0] tmp_32_reg_1120;
reg   [0:0] xs_sign_3_reg_1125;
wire   [0:0] tmp_14_fu_680_p3;
reg   [0:0] tmp_14_reg_1131;
wire   [8:0] select_ln18_6_fu_698_p3;
reg   [8:0] select_ln18_6_reg_1136;
wire   [31:0] val_2_fu_706_p3;
reg   [31:0] val_2_reg_1141;
wire    ap_CS_fsm_state21;
wire   [31:0] val_3_fu_763_p3;
reg   [31:0] val_3_reg_1148;
wire   [0:0] icmp_ln2815_fu_804_p2;
reg   [0:0] icmp_ln2815_reg_1155;
wire    ap_CS_fsm_state42;
wire   [0:0] icmp_ln2815_4_fu_810_p2;
reg   [0:0] icmp_ln2815_4_reg_1160;
wire   [63:0] grp_fu_375_p1;
reg   [63:0] conv_i_reg_1165;
wire    ap_CS_fsm_state43;
wire   [0:0] grp_fu_378_p2;
reg   [0:0] tmp_29_reg_1170;
wire   [63:0] select_ln2815_fu_825_p3;
wire    ap_CS_fsm_state44;
wire   [63:0] grp_fu_389_p2;
reg   [63:0] dc_reg_1180;
wire    ap_CS_fsm_state51;
wire   [26:0] grp_fu_770_p2;
reg   [26:0] sdiv_ln3417_reg_1185;
wire   [23:0] grp_fu_776_p2;
reg   [23:0] sdiv_ln3418_reg_1190;
wire   [0:0] tmp_fu_875_p3;
reg   [0:0] tmp_reg_1195;
wire    ap_CS_fsm_state52;
wire   [31:0] result_20_fu_926_p3;
reg   [31:0] result_20_reg_1200;
wire   [31:0] result_21_fu_938_p3;
reg   [31:0] result_21_reg_1206;
wire   [27:0] x_ratio_fu_965_p2;
reg   [27:0] x_ratio_reg_1212;
wire   [23:0] y_ratio_fu_988_p2;
reg   [23:0] y_ratio_reg_1217;
reg   [31:0] tmp_15_reg_1222;
reg   [31:0] tmp_16_reg_1227;
reg   [0:0] xs_sign_reg_1232;
wire   [31:0] result_19_fu_1034_p3;
reg   [31:0] result_19_reg_1237;
wire    ap_CS_fsm_state53;
reg   [6:0] result_x_Scale_address0;
reg    result_x_Scale_ce0;
reg    result_x_Scale_we0;
wire   [31:0] result_x_Scale_q0;
reg   [6:0] result_y_Scale_address0;
reg    result_y_Scale_ce0;
reg    result_y_Scale_we0;
wire   [31:0] result_y_Scale_q0;
reg   [6:0] result_w_Scale_address0;
reg    result_w_Scale_ce0;
reg    result_w_Scale_we0;
wire   [31:0] result_w_Scale_q0;
reg   [6:0] result_h_Scale_address0;
reg    result_h_Scale_ce0;
reg    result_h_Scale_we0;
wire   [31:0] result_h_Scale_q0;
reg   [16:0] IMG1_data_address0;
reg    IMG1_data_ce0;
reg    IMG1_data_we0;
wire   [7:0] IMG1_data_q0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_2850_1_fu_251_ap_start;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_2850_1_fu_251_ap_done;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_2850_1_fu_251_ap_idle;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_2850_1_fu_251_ap_ready;
wire   [8:0] grp_detectFaces_Pipeline_VITIS_LOOP_2850_1_fu_251_inData_address0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_2850_1_fu_251_inData_ce0;
wire   [16:0] grp_detectFaces_Pipeline_VITIS_LOOP_2850_1_fu_251_Data_address0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_2850_1_fu_251_Data_ce0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_2850_1_fu_251_Data_we0;
wire   [7:0] grp_detectFaces_Pipeline_VITIS_LOOP_2850_1_fu_251_Data_d0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_ap_start;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_ap_done;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_ap_idle;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_ap_ready;
wire   [6:0] grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_result_x_address0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_result_x_ce0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_result_x_we0;
wire   [31:0] grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_result_x_d0;
wire   [6:0] grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_result_y_address0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_result_y_ce0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_result_y_we0;
wire   [31:0] grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_result_y_d0;
wire   [6:0] grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_result_w_address0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_result_w_ce0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_result_w_we0;
wire   [31:0] grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_result_w_d0;
wire   [6:0] grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_result_h_address0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_result_h_ce0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_result_h_we0;
wire   [31:0] grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_result_h_d0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_ap_start;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_ap_done;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_ap_idle;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_ap_ready;
wire   [6:0] grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_x_Scale_address0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_x_Scale_ce0;
wire   [6:0] grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_x_address0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_x_ce0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_x_we0;
wire   [31:0] grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_x_d0;
wire   [6:0] grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_y_Scale_address0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_y_Scale_ce0;
wire   [6:0] grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_y_address0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_y_ce0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_y_we0;
wire   [31:0] grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_y_d0;
wire   [6:0] grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_w_Scale_address0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_w_Scale_ce0;
wire   [6:0] grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_w_address0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_w_ce0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_w_we0;
wire   [31:0] grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_w_d0;
wire   [6:0] grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_h_Scale_address0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_h_Scale_ce0;
wire   [6:0] grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_h_address0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_h_ce0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_h_we0;
wire   [31:0] grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_h_d0;
wire    grp_detectFaces_Pipeline_imageScalerL1_imageScalerL1_1_fu_288_ap_start;
wire    grp_detectFaces_Pipeline_imageScalerL1_imageScalerL1_1_fu_288_ap_done;
wire    grp_detectFaces_Pipeline_imageScalerL1_imageScalerL1_1_fu_288_ap_idle;
wire    grp_detectFaces_Pipeline_imageScalerL1_imageScalerL1_1_fu_288_ap_ready;
wire   [16:0] grp_detectFaces_Pipeline_imageScalerL1_imageScalerL1_1_fu_288_IMG1_data_address0;
wire    grp_detectFaces_Pipeline_imageScalerL1_imageScalerL1_1_fu_288_IMG1_data_ce0;
wire    grp_detectFaces_Pipeline_imageScalerL1_imageScalerL1_1_fu_288_IMG1_data_we0;
wire   [7:0] grp_detectFaces_Pipeline_imageScalerL1_imageScalerL1_1_fu_288_IMG1_data_d0;
wire   [16:0] grp_detectFaces_Pipeline_imageScalerL1_imageScalerL1_1_fu_288_Data_address0;
wire    grp_detectFaces_Pipeline_imageScalerL1_imageScalerL1_1_fu_288_Data_ce0;
wire    grp_processImage_fu_299_ap_start;
wire    grp_processImage_fu_299_ap_done;
wire    grp_processImage_fu_299_ap_idle;
wire    grp_processImage_fu_299_ap_ready;
wire   [6:0] grp_processImage_fu_299_AllCandidates_x_address0;
wire    grp_processImage_fu_299_AllCandidates_x_ce0;
wire    grp_processImage_fu_299_AllCandidates_x_we0;
wire   [31:0] grp_processImage_fu_299_AllCandidates_x_d0;
wire   [6:0] grp_processImage_fu_299_AllCandidates_y_address0;
wire    grp_processImage_fu_299_AllCandidates_y_ce0;
wire    grp_processImage_fu_299_AllCandidates_y_we0;
wire   [31:0] grp_processImage_fu_299_AllCandidates_y_d0;
wire   [6:0] grp_processImage_fu_299_AllCandidates_w_address0;
wire    grp_processImage_fu_299_AllCandidates_w_ce0;
wire    grp_processImage_fu_299_AllCandidates_w_we0;
wire   [31:0] grp_processImage_fu_299_AllCandidates_w_d0;
wire   [6:0] grp_processImage_fu_299_AllCandidates_h_address0;
wire    grp_processImage_fu_299_AllCandidates_h_ce0;
wire    grp_processImage_fu_299_AllCandidates_h_we0;
wire   [31:0] grp_processImage_fu_299_AllCandidates_h_d0;
wire   [16:0] grp_processImage_fu_299_IMG1_data_address0;
wire    grp_processImage_fu_299_IMG1_data_ce0;
wire   [31:0] grp_processImage_fu_299_ap_return;
wire   [31:0] grp_processImage_fu_299_grp_fu_359_p_din0;
wire   [31:0] grp_processImage_fu_299_grp_fu_359_p_din1;
wire    grp_processImage_fu_299_grp_fu_359_p_ce;
wire   [31:0] grp_processImage_fu_299_grp_fu_375_p_din0;
wire    grp_processImage_fu_299_grp_fu_375_p_ce;
wire   [31:0] grp_processImage_fu_299_grp_fu_378_p_din0;
wire   [31:0] grp_processImage_fu_299_grp_fu_378_p_din1;
wire   [4:0] grp_processImage_fu_299_grp_fu_378_p_opcode;
wire    grp_processImage_fu_299_grp_fu_378_p_ce;
wire   [31:0] grp_processImage_fu_299_grp_fu_383_p_din0;
wire   [31:0] grp_processImage_fu_299_grp_fu_383_p_din1;
wire   [4:0] grp_processImage_fu_299_grp_fu_383_p_opcode;
wire    grp_processImage_fu_299_grp_fu_383_p_ce;
wire   [63:0] grp_processImage_fu_299_grp_fu_389_p_din0;
wire   [63:0] grp_processImage_fu_299_grp_fu_389_p_din1;
wire   [1:0] grp_processImage_fu_299_grp_fu_389_p_opcode;
wire    grp_processImage_fu_299_grp_fu_389_p_ce;
reg   [31:0] storemerge_reg_239;
wire    ap_CS_fsm_state56;
wire    ap_CS_fsm_state57;
reg    grp_detectFaces_Pipeline_VITIS_LOOP_2850_1_fu_251_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_ap_start_reg;
reg    ap_block_state2_on_subcall_done;
reg    grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_ap_start_reg;
wire   [0:0] and_ln2885_fu_558_p2;
reg    grp_detectFaces_Pipeline_imageScalerL1_imageScalerL1_1_fu_288_ap_start_reg;
reg    grp_processImage_fu_299_ap_start_reg;
wire    ap_CS_fsm_state54;
wire    ap_CS_fsm_state55;
wire   [31:0] add_ln2853_fu_440_p2;
reg   [31:0] factor_fu_224;
wire    ap_CS_fsm_state24;
reg   [31:0] res_size_Scale_0_fu_228;
wire    ap_CS_fsm_state58;
reg   [31:0] grp_fu_359_p0;
reg   [31:0] grp_fu_359_p1;
wire    ap_CS_fsm_state38;
reg   [31:0] grp_fu_375_p0;
reg   [31:0] grp_fu_378_p0;
reg   [31:0] grp_fu_378_p1;
wire    ap_CS_fsm_state19;
reg   [31:0] grp_fu_383_p0;
reg   [31:0] grp_fu_383_p1;
reg   [63:0] grp_fu_389_p0;
reg   [63:0] grp_fu_389_p1;
wire   [8:0] trunc_ln2849_1_fu_407_p1;
wire   [10:0] trunc_ln2849_fu_403_p1;
wire   [16:0] tmp_s_fu_417_p3;
wire   [16:0] tmp_30_fu_425_p3;
wire   [31:0] data_2_fu_476_p1;
wire   [7:0] xs_exp_2_fu_479_p4;
wire   [22:0] trunc_ln2885_fu_489_p1;
wire   [0:0] icmp_ln2885_1_fu_499_p2;
wire   [0:0] icmp_ln2885_fu_493_p2;
wire   [0:0] or_ln2885_fu_505_p2;
wire   [31:0] data_3_fu_517_p1;
wire   [7:0] xs_exp_3_fu_520_p4;
wire   [0:0] icmp_ln2885_3_fu_540_p2;
wire   [0:0] icmp_ln2885_2_fu_534_p2;
wire   [0:0] or_ln2885_1_fu_546_p2;
wire   [0:0] grp_fu_383_p2;
wire   [0:0] and_ln2885_1_fu_511_p2;
wire   [0:0] and_ln2885_2_fu_552_p2;
wire   [24:0] mantissa_2_fu_572_p4;
wire   [8:0] zext_ln317_fu_586_p1;
wire   [8:0] add_ln317_fu_590_p2;
wire   [7:0] sub_ln18_2_fu_604_p2;
wire  signed [8:0] sext_ln18_5_fu_610_p1;
wire   [8:0] select_ln18_4_fu_614_p3;
wire  signed [31:0] sext_ln18_6_fu_622_p1;
wire   [78:0] zext_ln15_2_fu_582_p1;
wire   [78:0] zext_ln18_2_fu_626_p1;
wire   [78:0] lshr_ln18_2_fu_630_p2;
wire   [78:0] shl_ln18_2_fu_636_p2;
wire   [8:0] zext_ln317_1_fu_670_p1;
wire   [8:0] add_ln317_1_fu_674_p2;
wire   [7:0] sub_ln18_3_fu_688_p2;
wire  signed [8:0] sext_ln18_7_fu_694_p1;
wire   [24:0] mantissa_3_fu_711_p4;
wire  signed [31:0] sext_ln18_8_fu_724_p1;
wire   [78:0] zext_ln15_3_fu_720_p1;
wire   [78:0] zext_ln18_3_fu_727_p1;
wire   [78:0] lshr_ln18_3_fu_731_p2;
wire   [78:0] shl_ln18_3_fu_737_p2;
wire   [31:0] tmp_33_fu_743_p4;
wire   [31:0] tmp_34_fu_753_p4;
wire   [26:0] grp_fu_770_p0;
wire   [31:0] grp_fu_770_p1;
wire   [25:0] grp_fu_776_p0;
wire    ap_CS_fsm_state22;
wire   [31:0] bitcast_ln2815_fu_786_p1;
wire   [7:0] tmp_28_fu_790_p4;
wire   [22:0] trunc_ln2815_fu_800_p1;
wire   [0:0] or_ln2815_fu_816_p2;
wire   [0:0] and_ln2815_fu_820_p2;
wire   [63:0] data_fu_834_p1;
wire   [51:0] trunc_ln505_fu_847_p1;
wire   [53:0] mantissa_fu_851_p4;
wire   [10:0] xs_exp_fu_837_p4;
wire   [11:0] zext_ln486_fu_865_p1;
wire   [11:0] add_ln486_fu_869_p2;
wire   [10:0] sub_ln18_fu_883_p2;
wire  signed [11:0] sext_ln18_fu_889_p1;
wire   [11:0] select_ln18_fu_893_p3;
wire  signed [31:0] sext_ln18_4_fu_901_p1;
wire   [136:0] zext_ln15_fu_861_p1;
wire   [136:0] zext_ln18_fu_905_p1;
wire   [31:0] result_13_fu_921_p2;
wire   [31:0] result_17_fu_933_p2;
wire   [26:0] trunc_ln3417_fu_945_p1;
wire   [26:0] sub_ln3417_fu_948_p2;
wire   [26:0] select_ln3417_fu_954_p3;
wire  signed [27:0] sext_ln3417_fu_961_p1;
wire   [23:0] trunc_ln3418_fu_972_p1;
wire   [23:0] sub_ln3418_fu_975_p2;
wire   [23:0] select_ln3418_fu_981_p3;
wire   [136:0] lshr_ln18_fu_909_p2;
wire   [136:0] shl_ln18_fu_915_p2;
wire   [31:0] val_fu_1023_p3;
wire   [31:0] result_fu_1028_p2;
reg    grp_fu_359_ce;
reg    grp_fu_375_ce;
reg    grp_fu_378_ce;
reg   [4:0] grp_fu_378_opcode;
reg    grp_fu_383_ce;
reg   [4:0] grp_fu_383_opcode;
reg    grp_fu_389_ce;
reg    grp_fu_770_ap_start;
wire    grp_fu_770_ap_done;
reg    grp_fu_776_ap_start;
wire    grp_fu_776_ap_done;
reg   [57:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
wire    ap_ST_fsm_state44_blk;
wire    ap_ST_fsm_state45_blk;
wire    ap_ST_fsm_state46_blk;
wire    ap_ST_fsm_state47_blk;
wire    ap_ST_fsm_state48_blk;
wire    ap_ST_fsm_state49_blk;
wire    ap_ST_fsm_state50_blk;
wire    ap_ST_fsm_state51_blk;
wire    ap_ST_fsm_state52_blk;
reg    ap_ST_fsm_state53_blk;
wire    ap_ST_fsm_state54_blk;
reg    ap_ST_fsm_state55_blk;
reg    ap_ST_fsm_state56_blk;
reg    ap_ST_fsm_state57_blk;
wire    ap_ST_fsm_state58_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 58'd1;
#0 counter = 32'd0;
#0 grp_detectFaces_Pipeline_VITIS_LOOP_2850_1_fu_251_ap_start_reg = 1'b0;
#0 grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_ap_start_reg = 1'b0;
#0 grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_ap_start_reg = 1'b0;
#0 grp_detectFaces_Pipeline_imageScalerL1_imageScalerL1_1_fu_288_ap_start_reg = 1'b0;
#0 grp_processImage_fu_299_ap_start_reg = 1'b0;
#0 factor_fu_224 = 32'd0;
#0 res_size_Scale_0_fu_228 = 32'd0;
end

detectFaces_Data_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 76800 ),
    .AddressWidth( 17 ))
Data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(Data_address0),
    .ce0(Data_ce0),
    .we0(Data_we0),
    .d0(grp_detectFaces_Pipeline_VITIS_LOOP_2850_1_fu_251_Data_d0),
    .q0(Data_q0)
);

detectFaces_result_x_Scale_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
result_x_Scale_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(result_x_Scale_address0),
    .ce0(result_x_Scale_ce0),
    .we0(result_x_Scale_we0),
    .d0(grp_processImage_fu_299_AllCandidates_x_d0),
    .q0(result_x_Scale_q0)
);

detectFaces_result_x_Scale_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
result_y_Scale_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(result_y_Scale_address0),
    .ce0(result_y_Scale_ce0),
    .we0(result_y_Scale_we0),
    .d0(grp_processImage_fu_299_AllCandidates_y_d0),
    .q0(result_y_Scale_q0)
);

detectFaces_result_x_Scale_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
result_w_Scale_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(result_w_Scale_address0),
    .ce0(result_w_Scale_ce0),
    .we0(result_w_Scale_we0),
    .d0(grp_processImage_fu_299_AllCandidates_w_d0),
    .q0(result_w_Scale_q0)
);

detectFaces_result_x_Scale_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
result_h_Scale_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(result_h_Scale_address0),
    .ce0(result_h_Scale_ce0),
    .we0(result_h_Scale_we0),
    .d0(grp_processImage_fu_299_AllCandidates_h_d0),
    .q0(result_h_Scale_q0)
);

detectFaces_IMG1_data_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 76800 ),
    .AddressWidth( 17 ))
IMG1_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(IMG1_data_address0),
    .ce0(IMG1_data_ce0),
    .we0(IMG1_data_we0),
    .d0(grp_detectFaces_Pipeline_imageScalerL1_imageScalerL1_1_fu_288_IMG1_data_d0),
    .q0(IMG1_data_q0)
);

detectFaces_detectFaces_Pipeline_VITIS_LOOP_2850_1 grp_detectFaces_Pipeline_VITIS_LOOP_2850_1_fu_251(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_detectFaces_Pipeline_VITIS_LOOP_2850_1_fu_251_ap_start),
    .ap_done(grp_detectFaces_Pipeline_VITIS_LOOP_2850_1_fu_251_ap_done),
    .ap_idle(grp_detectFaces_Pipeline_VITIS_LOOP_2850_1_fu_251_ap_idle),
    .ap_ready(grp_detectFaces_Pipeline_VITIS_LOOP_2850_1_fu_251_ap_ready),
    .add_ln2851(add_ln2851_reg_1050),
    .inData_address0(grp_detectFaces_Pipeline_VITIS_LOOP_2850_1_fu_251_inData_address0),
    .inData_ce0(grp_detectFaces_Pipeline_VITIS_LOOP_2850_1_fu_251_inData_ce0),
    .inData_q0(inData_q0),
    .Data_address0(grp_detectFaces_Pipeline_VITIS_LOOP_2850_1_fu_251_Data_address0),
    .Data_ce0(grp_detectFaces_Pipeline_VITIS_LOOP_2850_1_fu_251_Data_ce0),
    .Data_we0(grp_detectFaces_Pipeline_VITIS_LOOP_2850_1_fu_251_Data_we0),
    .Data_d0(grp_detectFaces_Pipeline_VITIS_LOOP_2850_1_fu_251_Data_d0)
);

detectFaces_detectFaces_Pipeline_VITIS_LOOP_2855_2 grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_ap_start),
    .ap_done(grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_ap_done),
    .ap_idle(grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_ap_idle),
    .ap_ready(grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_ap_ready),
    .result_x_address0(grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_result_x_address0),
    .result_x_ce0(grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_result_x_ce0),
    .result_x_we0(grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_result_x_we0),
    .result_x_d0(grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_result_x_d0),
    .result_y_address0(grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_result_y_address0),
    .result_y_ce0(grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_result_y_ce0),
    .result_y_we0(grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_result_y_we0),
    .result_y_d0(grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_result_y_d0),
    .result_w_address0(grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_result_w_address0),
    .result_w_ce0(grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_result_w_ce0),
    .result_w_we0(grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_result_w_we0),
    .result_w_d0(grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_result_w_d0),
    .result_h_address0(grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_result_h_address0),
    .result_h_ce0(grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_result_h_ce0),
    .result_h_we0(grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_result_h_we0),
    .result_h_d0(grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_result_h_d0)
);

detectFaces_detectFaces_Pipeline_VITIS_LOOP_2922_3 grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_ap_start),
    .ap_done(grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_ap_done),
    .ap_idle(grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_ap_idle),
    .ap_ready(grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_ap_ready),
    .result_x_Scale_address0(grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_x_Scale_address0),
    .result_x_Scale_ce0(grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_x_Scale_ce0),
    .result_x_Scale_q0(result_x_Scale_q0),
    .result_x_address0(grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_x_address0),
    .result_x_ce0(grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_x_ce0),
    .result_x_we0(grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_x_we0),
    .result_x_d0(grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_x_d0),
    .result_y_Scale_address0(grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_y_Scale_address0),
    .result_y_Scale_ce0(grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_y_Scale_ce0),
    .result_y_Scale_q0(result_y_Scale_q0),
    .result_y_address0(grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_y_address0),
    .result_y_ce0(grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_y_ce0),
    .result_y_we0(grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_y_we0),
    .result_y_d0(grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_y_d0),
    .result_w_Scale_address0(grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_w_Scale_address0),
    .result_w_Scale_ce0(grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_w_Scale_ce0),
    .result_w_Scale_q0(result_w_Scale_q0),
    .result_w_address0(grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_w_address0),
    .result_w_ce0(grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_w_ce0),
    .result_w_we0(grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_w_we0),
    .result_w_d0(grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_w_d0),
    .result_h_Scale_address0(grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_h_Scale_address0),
    .result_h_Scale_ce0(grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_h_Scale_ce0),
    .result_h_Scale_q0(result_h_Scale_q0),
    .result_h_address0(grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_h_address0),
    .result_h_ce0(grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_h_ce0),
    .result_h_we0(grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_h_we0),
    .result_h_d0(grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_h_d0)
);

detectFaces_detectFaces_Pipeline_imageScalerL1_imageScalerL1_1 grp_detectFaces_Pipeline_imageScalerL1_imageScalerL1_1_fu_288(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_detectFaces_Pipeline_imageScalerL1_imageScalerL1_1_fu_288_ap_start),
    .ap_done(grp_detectFaces_Pipeline_imageScalerL1_imageScalerL1_1_fu_288_ap_done),
    .ap_idle(grp_detectFaces_Pipeline_imageScalerL1_imageScalerL1_1_fu_288_ap_idle),
    .ap_ready(grp_detectFaces_Pipeline_imageScalerL1_imageScalerL1_1_fu_288_ap_ready),
    .y_ratio(y_ratio_reg_1217),
    .result_16(result_21_reg_1206),
    .IMG1_data_address0(grp_detectFaces_Pipeline_imageScalerL1_imageScalerL1_1_fu_288_IMG1_data_address0),
    .IMG1_data_ce0(grp_detectFaces_Pipeline_imageScalerL1_imageScalerL1_1_fu_288_IMG1_data_ce0),
    .IMG1_data_we0(grp_detectFaces_Pipeline_imageScalerL1_imageScalerL1_1_fu_288_IMG1_data_we0),
    .IMG1_data_d0(grp_detectFaces_Pipeline_imageScalerL1_imageScalerL1_1_fu_288_IMG1_data_d0),
    .result_15(result_20_reg_1200),
    .sext_ln3417_1(x_ratio_reg_1212),
    .Data_address0(grp_detectFaces_Pipeline_imageScalerL1_imageScalerL1_1_fu_288_Data_address0),
    .Data_ce0(grp_detectFaces_Pipeline_imageScalerL1_imageScalerL1_1_fu_288_Data_ce0),
    .Data_q0(Data_q0)
);

detectFaces_processImage grp_processImage_fu_299(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_processImage_fu_299_ap_start),
    .ap_done(grp_processImage_fu_299_ap_done),
    .ap_idle(grp_processImage_fu_299_ap_idle),
    .ap_ready(grp_processImage_fu_299_ap_ready),
    .factor(factor_2_reg_1073),
    .sum_row(result_21_reg_1206),
    .sum_col(result_20_reg_1200),
    .AllCandidates_x_address0(grp_processImage_fu_299_AllCandidates_x_address0),
    .AllCandidates_x_ce0(grp_processImage_fu_299_AllCandidates_x_ce0),
    .AllCandidates_x_we0(grp_processImage_fu_299_AllCandidates_x_we0),
    .AllCandidates_x_d0(grp_processImage_fu_299_AllCandidates_x_d0),
    .AllCandidates_y_address0(grp_processImage_fu_299_AllCandidates_y_address0),
    .AllCandidates_y_ce0(grp_processImage_fu_299_AllCandidates_y_ce0),
    .AllCandidates_y_we0(grp_processImage_fu_299_AllCandidates_y_we0),
    .AllCandidates_y_d0(grp_processImage_fu_299_AllCandidates_y_d0),
    .AllCandidates_w_address0(grp_processImage_fu_299_AllCandidates_w_address0),
    .AllCandidates_w_ce0(grp_processImage_fu_299_AllCandidates_w_ce0),
    .AllCandidates_w_we0(grp_processImage_fu_299_AllCandidates_w_we0),
    .AllCandidates_w_d0(grp_processImage_fu_299_AllCandidates_w_d0),
    .AllCandidates_h_address0(grp_processImage_fu_299_AllCandidates_h_address0),
    .AllCandidates_h_ce0(grp_processImage_fu_299_AllCandidates_h_ce0),
    .AllCandidates_h_we0(grp_processImage_fu_299_AllCandidates_h_we0),
    .AllCandidates_h_d0(grp_processImage_fu_299_AllCandidates_h_d0),
    .p_read(res_size_Scale_0_fu_228),
    .IMG1_data_address0(grp_processImage_fu_299_IMG1_data_address0),
    .IMG1_data_ce0(grp_processImage_fu_299_IMG1_data_ce0),
    .IMG1_data_q0(IMG1_data_q0),
    .winSize_width_val(result_19_reg_1237),
    .ap_return(grp_processImage_fu_299_ap_return),
    .grp_fu_359_p_din0(grp_processImage_fu_299_grp_fu_359_p_din0),
    .grp_fu_359_p_din1(grp_processImage_fu_299_grp_fu_359_p_din1),
    .grp_fu_359_p_dout0(grp_fu_359_p2),
    .grp_fu_359_p_ce(grp_processImage_fu_299_grp_fu_359_p_ce),
    .grp_fu_375_p_din0(grp_processImage_fu_299_grp_fu_375_p_din0),
    .grp_fu_375_p_dout0(grp_fu_375_p1),
    .grp_fu_375_p_ce(grp_processImage_fu_299_grp_fu_375_p_ce),
    .grp_fu_378_p_din0(grp_processImage_fu_299_grp_fu_378_p_din0),
    .grp_fu_378_p_din1(grp_processImage_fu_299_grp_fu_378_p_din1),
    .grp_fu_378_p_opcode(grp_processImage_fu_299_grp_fu_378_p_opcode),
    .grp_fu_378_p_dout0(grp_fu_378_p2),
    .grp_fu_378_p_ce(grp_processImage_fu_299_grp_fu_378_p_ce),
    .grp_fu_383_p_din0(grp_processImage_fu_299_grp_fu_383_p_din0),
    .grp_fu_383_p_din1(grp_processImage_fu_299_grp_fu_383_p_din1),
    .grp_fu_383_p_opcode(grp_processImage_fu_299_grp_fu_383_p_opcode),
    .grp_fu_383_p_dout0(grp_fu_383_p2),
    .grp_fu_383_p_ce(grp_processImage_fu_299_grp_fu_383_p_ce),
    .grp_fu_389_p_din0(grp_processImage_fu_299_grp_fu_389_p_din0),
    .grp_fu_389_p_din1(grp_processImage_fu_299_grp_fu_389_p_din1),
    .grp_fu_389_p_opcode(grp_processImage_fu_299_grp_fu_389_p_opcode),
    .grp_fu_389_p_dout0(grp_fu_389_p2),
    .grp_fu_389_p_ce(grp_processImage_fu_299_grp_fu_389_p_ce)
);

detectFaces_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U860(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_359_p0),
    .din1(grp_fu_359_p1),
    .ce(grp_fu_359_ce),
    .dout(grp_fu_359_p2)
);

detectFaces_fdiv_32ns_32ns_32_16_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 16 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fdiv_32ns_32ns_32_16_no_dsp_1_U861(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd1134559232),
    .din1(factor_fu_224),
    .ce(1'b1),
    .dout(grp_fu_365_p2)
);

detectFaces_fdiv_32ns_32ns_32_16_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 16 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fdiv_32ns_32ns_32_16_no_dsp_1_U862(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd1131413504),
    .din1(factor_fu_224),
    .ce(1'b1),
    .dout(grp_fu_370_p2)
);

detectFaces_fpext_32ns_64_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
fpext_32ns_64_2_no_dsp_1_U863(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_375_p0),
    .ce(grp_fu_375_ce),
    .dout(grp_fu_375_p1)
);

detectFaces_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U864(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_378_p0),
    .din1(grp_fu_378_p1),
    .ce(grp_fu_378_ce),
    .opcode(grp_fu_378_opcode),
    .dout(grp_fu_378_p2)
);

detectFaces_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U865(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_383_p0),
    .din1(grp_fu_383_p1),
    .ce(grp_fu_383_ce),
    .opcode(grp_fu_383_opcode),
    .dout(grp_fu_383_p2)
);

detectFaces_dadd_64ns_64ns_64_8_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dadd_64ns_64ns_64_8_full_dsp_1_U866(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_389_p0),
    .din1(grp_fu_389_p1),
    .ce(grp_fu_389_ce),
    .dout(grp_fu_389_p2)
);

detectFaces_sdiv_27ns_32ns_27_31_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 31 ),
    .din0_WIDTH( 27 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 27 ))
sdiv_27ns_32ns_27_31_seq_1_U867(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_770_ap_start),
    .done(grp_fu_770_ap_done),
    .din0(grp_fu_770_p0),
    .din1(grp_fu_770_p1),
    .ce(1'b1),
    .dout(grp_fu_770_p2)
);

detectFaces_sdiv_26ns_32ns_24_30_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 30 ),
    .din0_WIDTH( 26 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 24 ))
sdiv_26ns_32ns_24_30_seq_1_U868(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_776_ap_start),
    .done(grp_fu_776_ap_done),
    .din0(grp_fu_776_p0),
    .din1(val_3_reg_1148),
    .ce(1'b1),
    .dout(grp_fu_776_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_detectFaces_Pipeline_VITIS_LOOP_2850_1_fu_251_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln2849_fu_411_p2 == 1'd1))) begin
            grp_detectFaces_Pipeline_VITIS_LOOP_2850_1_fu_251_ap_start_reg <= 1'b1;
        end else if ((grp_detectFaces_Pipeline_VITIS_LOOP_2850_1_fu_251_ap_ready == 1'b1)) begin
            grp_detectFaces_Pipeline_VITIS_LOOP_2850_1_fu_251_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln2854_reg_1055 == 1'd1) & (icmp_ln2849_reg_1046 == 1'd1))) begin
            grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_ap_start_reg <= 1'b1;
        end else if ((grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_ap_ready == 1'b1)) begin
            grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_ap_start_reg <= 1'b0;
    end else begin
        if (((1'd0 == and_ln2885_fu_558_p2) & (1'b1 == ap_CS_fsm_state20))) begin
            grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_ap_start_reg <= 1'b1;
        end else if ((grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_ap_ready == 1'b1)) begin
            grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_detectFaces_Pipeline_imageScalerL1_imageScalerL1_1_fu_288_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state52)) begin
            grp_detectFaces_Pipeline_imageScalerL1_imageScalerL1_1_fu_288_ap_start_reg <= 1'b1;
        end else if ((grp_detectFaces_Pipeline_imageScalerL1_imageScalerL1_1_fu_288_ap_ready == 1'b1)) begin
            grp_detectFaces_Pipeline_imageScalerL1_imageScalerL1_1_fu_288_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_processImage_fu_299_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state54)) begin
            grp_processImage_fu_299_ap_start_reg <= 1'b1;
        end else if ((grp_processImage_fu_299_ap_ready == 1'b1)) begin
            grp_processImage_fu_299_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2) & ((icmp_ln2854_reg_1055 == 1'd0) | (icmp_ln2849_reg_1046 == 1'd0)))) begin
        factor_fu_224 <= 32'd1065353216;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        factor_fu_224 <= reg_393;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2) & ((icmp_ln2854_reg_1055 == 1'd0) | (icmp_ln2849_reg_1046 == 1'd0)))) begin
        res_size_Scale_0_fu_228 <= 32'd0;
    end else if (((grp_processImage_fu_299_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state55))) begin
        res_size_Scale_0_fu_228 <= grp_processImage_fu_299_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state57))) begin
        storemerge_reg_239 <= 32'd0;
    end else if (((grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state56))) begin
        storemerge_reg_239 <= res_size_Scale_0_load_reg_1091;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        add_ln2851_reg_1050[16 : 6] <= add_ln2851_fu_433_p2[16 : 6];
        icmp_ln2849_reg_1046 <= icmp_ln2849_fu_411_p2;
        icmp_ln2854_reg_1055 <= icmp_ln2854_fu_452_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state43)) begin
        conv_i_reg_1165 <= grp_fu_375_p1;
        tmp_29_reg_1170 <= grp_fu_378_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln2849_fu_411_p2 == 1'd1))) begin
        counter <= add_ln2853_fu_440_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        dc_2_reg_1079 <= grp_fu_365_p2;
        dc_3_reg_1085 <= grp_fu_370_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state51)) begin
        dc_reg_1180 <= grp_fu_389_p2;
        sdiv_ln3417_reg_1185 <= grp_fu_770_p2;
        sdiv_ln3418_reg_1190 <= grp_fu_776_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        factor_2_reg_1073 <= factor_fu_224;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state42)) begin
        icmp_ln2815_4_reg_1160 <= icmp_ln2815_4_fu_810_p2;
        icmp_ln2815_reg_1155 <= icmp_ln2815_fu_804_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state23))) begin
        reg_393 <= grp_fu_359_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        res_size_Scale_0_load_reg_1091 <= res_size_Scale_0_fu_228;
        select_ln18_6_reg_1136 <= select_ln18_6_fu_698_p3;
        tmp_12_reg_1110 <= add_ln317_fu_590_p2[32'd8];
        tmp_14_reg_1131 <= add_ln317_1_fu_674_p2[32'd8];
        tmp_31_reg_1115 <= {{lshr_ln18_2_fu_630_p2[55:24]}};
        tmp_32_reg_1120 <= {{shl_ln18_2_fu_636_p2[55:24]}};
        trunc_ln2885_1_reg_1096 <= trunc_ln2885_1_fu_530_p1;
        xs_sign_2_reg_1104 <= data_2_fu_476_p1[32'd31];
        xs_sign_3_reg_1125 <= data_3_fu_517_p1[32'd31];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state53)) begin
        result_19_reg_1237 <= result_19_fu_1034_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state52)) begin
        result_20_reg_1200 <= result_20_fu_926_p3;
        result_21_reg_1206 <= result_21_fu_938_p3;
        tmp_15_reg_1222 <= {{lshr_ln18_fu_909_p2[84:53]}};
        tmp_16_reg_1227 <= {{shl_ln18_fu_915_p2[84:53]}};
        tmp_reg_1195 <= add_ln486_fu_869_p2[32'd11];
        x_ratio_reg_1212 <= x_ratio_fu_965_p2;
        xs_sign_reg_1232 <= data_fu_834_p1[32'd63];
        y_ratio_reg_1217 <= y_ratio_fu_988_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        val_2_reg_1141 <= val_2_fu_706_p3;
        val_3_reg_1148 <= val_3_fu_763_p3;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state53)) begin
        Data_address0 = grp_detectFaces_Pipeline_imageScalerL1_imageScalerL1_1_fu_288_Data_address0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln2849_reg_1046 == 1'd1))) begin
        Data_address0 = grp_detectFaces_Pipeline_VITIS_LOOP_2850_1_fu_251_Data_address0;
    end else begin
        Data_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state53)) begin
        Data_ce0 = grp_detectFaces_Pipeline_imageScalerL1_imageScalerL1_1_fu_288_Data_ce0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln2849_reg_1046 == 1'd1))) begin
        Data_ce0 = grp_detectFaces_Pipeline_VITIS_LOOP_2850_1_fu_251_Data_ce0;
    end else begin
        Data_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln2849_reg_1046 == 1'd1))) begin
        Data_we0 = grp_detectFaces_Pipeline_VITIS_LOOP_2850_1_fu_251_Data_we0;
    end else begin
        Data_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state55)) begin
        IMG1_data_address0 = grp_processImage_fu_299_IMG1_data_address0;
    end else if ((1'b1 == ap_CS_fsm_state53)) begin
        IMG1_data_address0 = grp_detectFaces_Pipeline_imageScalerL1_imageScalerL1_1_fu_288_IMG1_data_address0;
    end else begin
        IMG1_data_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state55)) begin
        IMG1_data_ce0 = grp_processImage_fu_299_IMG1_data_ce0;
    end else if ((1'b1 == ap_CS_fsm_state53)) begin
        IMG1_data_ce0 = grp_detectFaces_Pipeline_imageScalerL1_imageScalerL1_1_fu_288_IMG1_data_ce0;
    end else begin
        IMG1_data_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state53)) begin
        IMG1_data_we0 = grp_detectFaces_Pipeline_imageScalerL1_imageScalerL1_1_fu_288_IMG1_data_we0;
    end else begin
        IMG1_data_we0 = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state2_on_subcall_done)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

assign ap_ST_fsm_state44_blk = 1'b0;

assign ap_ST_fsm_state45_blk = 1'b0;

assign ap_ST_fsm_state46_blk = 1'b0;

assign ap_ST_fsm_state47_blk = 1'b0;

assign ap_ST_fsm_state48_blk = 1'b0;

assign ap_ST_fsm_state49_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state50_blk = 1'b0;

assign ap_ST_fsm_state51_blk = 1'b0;

assign ap_ST_fsm_state52_blk = 1'b0;

always @ (*) begin
    if ((grp_detectFaces_Pipeline_imageScalerL1_imageScalerL1_1_fu_288_ap_done == 1'b0)) begin
        ap_ST_fsm_state53_blk = 1'b1;
    end else begin
        ap_ST_fsm_state53_blk = 1'b0;
    end
end

assign ap_ST_fsm_state54_blk = 1'b0;

always @ (*) begin
    if ((grp_processImage_fu_299_ap_done == 1'b0)) begin
        ap_ST_fsm_state55_blk = 1'b1;
    end else begin
        ap_ST_fsm_state55_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_ap_done == 1'b0)) begin
        ap_ST_fsm_state56_blk = 1'b1;
    end else begin
        ap_ST_fsm_state56_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_ap_done == 1'b0)) begin
        ap_ST_fsm_state57_blk = 1'b1;
    end else begin
        ap_ST_fsm_state57_blk = 1'b0;
    end
end

assign ap_ST_fsm_state58_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state58)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state58)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state55)) begin
        grp_fu_359_ce = grp_processImage_fu_299_grp_fu_359_p_ce;
    end else begin
        grp_fu_359_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state55)) begin
        grp_fu_359_p0 = grp_processImage_fu_299_grp_fu_359_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state38)) begin
        grp_fu_359_p0 = factor_2_reg_1073;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        grp_fu_359_p0 = factor_fu_224;
    end else begin
        grp_fu_359_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state55)) begin
        grp_fu_359_p1 = grp_processImage_fu_299_grp_fu_359_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state38)) begin
        grp_fu_359_p1 = 32'd1103101952;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        grp_fu_359_p1 = 32'd1067030938;
    end else begin
        grp_fu_359_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state55)) begin
        grp_fu_375_ce = grp_processImage_fu_299_grp_fu_375_p_ce;
    end else begin
        grp_fu_375_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state55)) begin
        grp_fu_375_p0 = grp_processImage_fu_299_grp_fu_375_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state42)) begin
        grp_fu_375_p0 = reg_393;
    end else begin
        grp_fu_375_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state55)) begin
        grp_fu_378_ce = grp_processImage_fu_299_grp_fu_378_p_ce;
    end else begin
        grp_fu_378_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state55)) begin
        grp_fu_378_opcode = grp_processImage_fu_299_grp_fu_378_p_opcode;
    end else if ((1'b1 == ap_CS_fsm_state42)) begin
        grp_fu_378_opcode = 5'd3;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        grp_fu_378_opcode = 5'd2;
    end else begin
        grp_fu_378_opcode = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state55)) begin
        grp_fu_378_p0 = grp_processImage_fu_299_grp_fu_378_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state42)) begin
        grp_fu_378_p0 = reg_393;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        grp_fu_378_p0 = dc_2_reg_1079;
    end else begin
        grp_fu_378_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state55)) begin
        grp_fu_378_p1 = grp_processImage_fu_299_grp_fu_378_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state42)) begin
        grp_fu_378_p1 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        grp_fu_378_p1 = 32'd1103626240;
    end else begin
        grp_fu_378_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state55)) begin
        grp_fu_383_ce = grp_processImage_fu_299_grp_fu_383_p_ce;
    end else begin
        grp_fu_383_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state55)) begin
        grp_fu_383_opcode = grp_processImage_fu_299_grp_fu_383_p_opcode;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        grp_fu_383_opcode = 5'd2;
    end else begin
        grp_fu_383_opcode = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state55)) begin
        grp_fu_383_p0 = grp_processImage_fu_299_grp_fu_383_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        grp_fu_383_p0 = dc_3_reg_1085;
    end else begin
        grp_fu_383_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state55)) begin
        grp_fu_383_p1 = grp_processImage_fu_299_grp_fu_383_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        grp_fu_383_p1 = 32'd1103626240;
    end else begin
        grp_fu_383_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state55)) begin
        grp_fu_389_ce = grp_processImage_fu_299_grp_fu_389_p_ce;
    end else begin
        grp_fu_389_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state55)) begin
        grp_fu_389_p0 = grp_processImage_fu_299_grp_fu_389_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state44)) begin
        grp_fu_389_p0 = conv_i_reg_1165;
    end else begin
        grp_fu_389_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state55)) begin
        grp_fu_389_p1 = grp_processImage_fu_299_grp_fu_389_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state44)) begin
        grp_fu_389_p1 = select_ln2815_fu_825_p3;
    end else begin
        grp_fu_389_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        grp_fu_770_ap_start = 1'b1;
    end else begin
        grp_fu_770_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        grp_fu_776_ap_start = 1'b1;
    end else begin
        grp_fu_776_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state55)) begin
        result_h_Scale_address0 = grp_processImage_fu_299_AllCandidates_h_address0;
    end else if ((1'b1 == ap_CS_fsm_state56)) begin
        result_h_Scale_address0 = grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_h_Scale_address0;
    end else begin
        result_h_Scale_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state55)) begin
        result_h_Scale_ce0 = grp_processImage_fu_299_AllCandidates_h_ce0;
    end else if ((1'b1 == ap_CS_fsm_state56)) begin
        result_h_Scale_ce0 = grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_h_Scale_ce0;
    end else begin
        result_h_Scale_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state55)) begin
        result_h_Scale_we0 = grp_processImage_fu_299_AllCandidates_h_we0;
    end else begin
        result_h_Scale_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        result_h_address0 = grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_h_address0;
    end else if ((1'b1 == ap_CS_fsm_state57)) begin
        result_h_address0 = grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_result_h_address0;
    end else begin
        result_h_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        result_h_ce0 = grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_h_ce0;
    end else if ((1'b1 == ap_CS_fsm_state57)) begin
        result_h_ce0 = grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_result_h_ce0;
    end else begin
        result_h_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        result_h_d0 = grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_h_d0;
    end else if ((1'b1 == ap_CS_fsm_state57)) begin
        result_h_d0 = grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_result_h_d0;
    end else begin
        result_h_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        result_h_we0 = grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_h_we0;
    end else if ((1'b1 == ap_CS_fsm_state57)) begin
        result_h_we0 = grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_result_h_we0;
    end else begin
        result_h_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state58)) begin
        result_size_ap_vld = 1'b1;
    end else begin
        result_size_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state55)) begin
        result_w_Scale_address0 = grp_processImage_fu_299_AllCandidates_w_address0;
    end else if ((1'b1 == ap_CS_fsm_state56)) begin
        result_w_Scale_address0 = grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_w_Scale_address0;
    end else begin
        result_w_Scale_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state55)) begin
        result_w_Scale_ce0 = grp_processImage_fu_299_AllCandidates_w_ce0;
    end else if ((1'b1 == ap_CS_fsm_state56)) begin
        result_w_Scale_ce0 = grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_w_Scale_ce0;
    end else begin
        result_w_Scale_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state55)) begin
        result_w_Scale_we0 = grp_processImage_fu_299_AllCandidates_w_we0;
    end else begin
        result_w_Scale_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        result_w_address0 = grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_w_address0;
    end else if ((1'b1 == ap_CS_fsm_state57)) begin
        result_w_address0 = grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_result_w_address0;
    end else begin
        result_w_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        result_w_ce0 = grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_w_ce0;
    end else if ((1'b1 == ap_CS_fsm_state57)) begin
        result_w_ce0 = grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_result_w_ce0;
    end else begin
        result_w_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        result_w_d0 = grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_w_d0;
    end else if ((1'b1 == ap_CS_fsm_state57)) begin
        result_w_d0 = grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_result_w_d0;
    end else begin
        result_w_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        result_w_we0 = grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_w_we0;
    end else if ((1'b1 == ap_CS_fsm_state57)) begin
        result_w_we0 = grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_result_w_we0;
    end else begin
        result_w_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state55)) begin
        result_x_Scale_address0 = grp_processImage_fu_299_AllCandidates_x_address0;
    end else if ((1'b1 == ap_CS_fsm_state56)) begin
        result_x_Scale_address0 = grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_x_Scale_address0;
    end else begin
        result_x_Scale_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state55)) begin
        result_x_Scale_ce0 = grp_processImage_fu_299_AllCandidates_x_ce0;
    end else if ((1'b1 == ap_CS_fsm_state56)) begin
        result_x_Scale_ce0 = grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_x_Scale_ce0;
    end else begin
        result_x_Scale_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state55)) begin
        result_x_Scale_we0 = grp_processImage_fu_299_AllCandidates_x_we0;
    end else begin
        result_x_Scale_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        result_x_address0 = grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_x_address0;
    end else if ((1'b1 == ap_CS_fsm_state57)) begin
        result_x_address0 = grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_result_x_address0;
    end else begin
        result_x_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        result_x_ce0 = grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_x_ce0;
    end else if ((1'b1 == ap_CS_fsm_state57)) begin
        result_x_ce0 = grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_result_x_ce0;
    end else begin
        result_x_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        result_x_d0 = grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_x_d0;
    end else if ((1'b1 == ap_CS_fsm_state57)) begin
        result_x_d0 = grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_result_x_d0;
    end else begin
        result_x_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        result_x_we0 = grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_x_we0;
    end else if ((1'b1 == ap_CS_fsm_state57)) begin
        result_x_we0 = grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_result_x_we0;
    end else begin
        result_x_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state55)) begin
        result_y_Scale_address0 = grp_processImage_fu_299_AllCandidates_y_address0;
    end else if ((1'b1 == ap_CS_fsm_state56)) begin
        result_y_Scale_address0 = grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_y_Scale_address0;
    end else begin
        result_y_Scale_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state55)) begin
        result_y_Scale_ce0 = grp_processImage_fu_299_AllCandidates_y_ce0;
    end else if ((1'b1 == ap_CS_fsm_state56)) begin
        result_y_Scale_ce0 = grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_y_Scale_ce0;
    end else begin
        result_y_Scale_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state55)) begin
        result_y_Scale_we0 = grp_processImage_fu_299_AllCandidates_y_we0;
    end else begin
        result_y_Scale_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        result_y_address0 = grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_y_address0;
    end else if ((1'b1 == ap_CS_fsm_state57)) begin
        result_y_address0 = grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_result_y_address0;
    end else begin
        result_y_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        result_y_ce0 = grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_y_ce0;
    end else if ((1'b1 == ap_CS_fsm_state57)) begin
        result_y_ce0 = grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_result_y_ce0;
    end else begin
        result_y_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        result_y_d0 = grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_y_d0;
    end else if ((1'b1 == ap_CS_fsm_state57)) begin
        result_y_d0 = grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_result_y_d0;
    end else begin
        result_y_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        result_y_we0 = grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_result_y_we0;
    end else if ((1'b1 == ap_CS_fsm_state57)) begin
        result_y_we0 = grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_result_y_we0;
    end else begin
        result_y_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2) & ((icmp_ln2854_reg_1055 == 1'd0) | (icmp_ln2849_reg_1046 == 1'd0)))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln2854_reg_1055 == 1'd1) & (icmp_ln2849_reg_1046 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state57;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            if (((1'd0 == and_ln2885_fu_558_p2) & (1'b1 == ap_CS_fsm_state20))) begin
                ap_NS_fsm = ap_ST_fsm_state56;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            if (((grp_detectFaces_Pipeline_imageScalerL1_imageScalerL1_1_fu_288_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state53))) begin
                ap_NS_fsm = ap_ST_fsm_state54;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state53;
            end
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            if (((grp_processImage_fu_299_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state55))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state55;
            end
        end
        ap_ST_fsm_state56 : begin
            if (((grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state56))) begin
                ap_NS_fsm = ap_ST_fsm_state58;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state56;
            end
        end
        ap_ST_fsm_state57 : begin
            if (((grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state57))) begin
                ap_NS_fsm = ap_ST_fsm_state58;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state57;
            end
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln2851_fu_433_p2 = (tmp_s_fu_417_p3 + tmp_30_fu_425_p3);

assign add_ln2853_fu_440_p2 = (counter + 32'd1);

assign add_ln317_1_fu_674_p2 = ($signed(zext_ln317_1_fu_670_p1) + $signed(9'd385));

assign add_ln317_fu_590_p2 = ($signed(zext_ln317_fu_586_p1) + $signed(9'd385));

assign add_ln486_fu_869_p2 = ($signed(zext_ln486_fu_865_p1) + $signed(12'd3073));

assign and_ln2815_fu_820_p2 = (tmp_29_reg_1170 & or_ln2815_fu_816_p2);

assign and_ln2885_1_fu_511_p2 = (or_ln2885_fu_505_p2 & grp_fu_378_p2);

assign and_ln2885_2_fu_552_p2 = (or_ln2885_1_fu_546_p2 & grp_fu_383_p2);

assign and_ln2885_fu_558_p2 = (and_ln2885_2_fu_552_p2 & and_ln2885_1_fu_511_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state38 = ap_CS_fsm[32'd37];

assign ap_CS_fsm_state41 = ap_CS_fsm[32'd40];

assign ap_CS_fsm_state42 = ap_CS_fsm[32'd41];

assign ap_CS_fsm_state43 = ap_CS_fsm[32'd42];

assign ap_CS_fsm_state44 = ap_CS_fsm[32'd43];

assign ap_CS_fsm_state51 = ap_CS_fsm[32'd50];

assign ap_CS_fsm_state52 = ap_CS_fsm[32'd51];

assign ap_CS_fsm_state53 = ap_CS_fsm[32'd52];

assign ap_CS_fsm_state54 = ap_CS_fsm[32'd53];

assign ap_CS_fsm_state55 = ap_CS_fsm[32'd54];

assign ap_CS_fsm_state56 = ap_CS_fsm[32'd55];

assign ap_CS_fsm_state57 = ap_CS_fsm[32'd56];

assign ap_CS_fsm_state58 = ap_CS_fsm[32'd57];

always @ (*) begin
    ap_block_state2_on_subcall_done = ((grp_detectFaces_Pipeline_VITIS_LOOP_2850_1_fu_251_ap_done == 1'b0) & (icmp_ln2849_reg_1046 == 1'd1));
end

assign bitcast_ln2815_fu_786_p1 = reg_393;

assign data_2_fu_476_p1 = dc_2_reg_1079;

assign data_3_fu_517_p1 = dc_3_reg_1085;

assign data_fu_834_p1 = dc_reg_1180;

assign grp_detectFaces_Pipeline_VITIS_LOOP_2850_1_fu_251_ap_start = grp_detectFaces_Pipeline_VITIS_LOOP_2850_1_fu_251_ap_start_reg;

assign grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_ap_start = grp_detectFaces_Pipeline_VITIS_LOOP_2855_2_fu_260_ap_start_reg;

assign grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_ap_start = grp_detectFaces_Pipeline_VITIS_LOOP_2922_3_fu_272_ap_start_reg;

assign grp_detectFaces_Pipeline_imageScalerL1_imageScalerL1_1_fu_288_ap_start = grp_detectFaces_Pipeline_imageScalerL1_imageScalerL1_1_fu_288_ap_start_reg;

assign grp_fu_770_p0 = 32'd20971520;

assign grp_fu_770_p1 = ((tmp_12_reg_1110[0:0] == 1'b1) ? tmp_31_reg_1115 : tmp_32_reg_1120);

assign grp_fu_776_p0 = 32'd15728640;

assign grp_processImage_fu_299_ap_start = grp_processImage_fu_299_ap_start_reg;

assign icmp_ln2815_4_fu_810_p2 = ((trunc_ln2815_fu_800_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln2815_fu_804_p2 = ((tmp_28_fu_790_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln2849_fu_411_p2 = (($signed(counter) < $signed(32'd240)) ? 1'b1 : 1'b0);

assign icmp_ln2854_fu_452_p2 = (($signed(add_ln2853_fu_440_p2) < $signed(32'd240)) ? 1'b1 : 1'b0);

assign icmp_ln2885_1_fu_499_p2 = ((trunc_ln2885_fu_489_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln2885_2_fu_534_p2 = ((xs_exp_3_fu_520_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln2885_3_fu_540_p2 = ((trunc_ln2885_1_fu_530_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln2885_fu_493_p2 = ((xs_exp_2_fu_479_p4 != 8'd255) ? 1'b1 : 1'b0);

assign inData_address0 = grp_detectFaces_Pipeline_VITIS_LOOP_2850_1_fu_251_inData_address0;

assign inData_ce0 = grp_detectFaces_Pipeline_VITIS_LOOP_2850_1_fu_251_inData_ce0;

assign lshr_ln18_2_fu_630_p2 = zext_ln15_2_fu_582_p1 >> zext_ln18_2_fu_626_p1;

assign lshr_ln18_3_fu_731_p2 = zext_ln15_3_fu_720_p1 >> zext_ln18_3_fu_727_p1;

assign lshr_ln18_fu_909_p2 = zext_ln15_fu_861_p1 >> zext_ln18_fu_905_p1;

assign mantissa_2_fu_572_p4 = {{{{1'd1}, {trunc_ln2885_fu_489_p1}}}, {1'd0}};

assign mantissa_3_fu_711_p4 = {{{{1'd1}, {trunc_ln2885_1_reg_1096}}}, {1'd0}};

assign mantissa_fu_851_p4 = {{{{1'd1}, {trunc_ln505_fu_847_p1}}}, {1'd0}};

assign or_ln2815_fu_816_p2 = (icmp_ln2815_reg_1155 | icmp_ln2815_4_reg_1160);

assign or_ln2885_1_fu_546_p2 = (icmp_ln2885_3_fu_540_p2 | icmp_ln2885_2_fu_534_p2);

assign or_ln2885_fu_505_p2 = (icmp_ln2885_fu_493_p2 | icmp_ln2885_1_fu_499_p2);

assign result_13_fu_921_p2 = (32'd0 - val_2_reg_1141);

assign result_17_fu_933_p2 = (32'd0 - val_3_reg_1148);

assign result_19_fu_1034_p3 = ((xs_sign_reg_1232[0:0] == 1'b1) ? result_fu_1028_p2 : val_fu_1023_p3);

assign result_20_fu_926_p3 = ((xs_sign_2_reg_1104[0:0] == 1'b1) ? result_13_fu_921_p2 : val_2_reg_1141);

assign result_21_fu_938_p3 = ((xs_sign_3_reg_1125[0:0] == 1'b1) ? result_17_fu_933_p2 : val_3_reg_1148);

assign result_fu_1028_p2 = (32'd0 - val_fu_1023_p3);

assign result_size = storemerge_reg_239;

assign select_ln18_4_fu_614_p3 = ((tmp_12_fu_596_p3[0:0] == 1'b1) ? sext_ln18_5_fu_610_p1 : add_ln317_fu_590_p2);

assign select_ln18_6_fu_698_p3 = ((tmp_14_fu_680_p3[0:0] == 1'b1) ? sext_ln18_7_fu_694_p1 : add_ln317_1_fu_674_p2);

assign select_ln18_fu_893_p3 = ((tmp_fu_875_p3[0:0] == 1'b1) ? sext_ln18_fu_889_p1 : add_ln486_fu_869_p2);

assign select_ln2815_fu_825_p3 = ((and_ln2815_fu_820_p2[0:0] == 1'b1) ? 64'd4602678819172646912 : 64'd13826050856027422720);

assign select_ln3417_fu_954_p3 = ((xs_sign_2_reg_1104[0:0] == 1'b1) ? sub_ln3417_fu_948_p2 : trunc_ln3417_fu_945_p1);

assign select_ln3418_fu_981_p3 = ((xs_sign_3_reg_1125[0:0] == 1'b1) ? sub_ln3418_fu_975_p2 : trunc_ln3418_fu_972_p1);

assign sext_ln18_4_fu_901_p1 = $signed(select_ln18_fu_893_p3);

assign sext_ln18_5_fu_610_p1 = $signed(sub_ln18_2_fu_604_p2);

assign sext_ln18_6_fu_622_p1 = $signed(select_ln18_4_fu_614_p3);

assign sext_ln18_7_fu_694_p1 = $signed(sub_ln18_3_fu_688_p2);

assign sext_ln18_8_fu_724_p1 = $signed(select_ln18_6_reg_1136);

assign sext_ln18_fu_889_p1 = $signed(sub_ln18_fu_883_p2);

assign sext_ln3417_fu_961_p1 = $signed(select_ln3417_fu_954_p3);

assign shl_ln18_2_fu_636_p2 = zext_ln15_2_fu_582_p1 << zext_ln18_2_fu_626_p1;

assign shl_ln18_3_fu_737_p2 = zext_ln15_3_fu_720_p1 << zext_ln18_3_fu_727_p1;

assign shl_ln18_fu_915_p2 = zext_ln15_fu_861_p1 << zext_ln18_fu_905_p1;

assign sub_ln18_2_fu_604_p2 = (8'd127 - xs_exp_2_fu_479_p4);

assign sub_ln18_3_fu_688_p2 = (8'd127 - xs_exp_3_fu_520_p4);

assign sub_ln18_fu_883_p2 = (11'd1023 - xs_exp_fu_837_p4);

assign sub_ln3417_fu_948_p2 = (27'd0 - trunc_ln3417_fu_945_p1);

assign sub_ln3418_fu_975_p2 = (24'd0 - trunc_ln3418_fu_972_p1);

assign tmp_12_fu_596_p3 = add_ln317_fu_590_p2[32'd8];

assign tmp_14_fu_680_p3 = add_ln317_1_fu_674_p2[32'd8];

assign tmp_28_fu_790_p4 = {{bitcast_ln2815_fu_786_p1[30:23]}};

assign tmp_30_fu_425_p3 = {{trunc_ln2849_fu_403_p1}, {6'd0}};

assign tmp_33_fu_743_p4 = {{lshr_ln18_3_fu_731_p2[55:24]}};

assign tmp_34_fu_753_p4 = {{shl_ln18_3_fu_737_p2[55:24]}};

assign tmp_fu_875_p3 = add_ln486_fu_869_p2[32'd11];

assign tmp_s_fu_417_p3 = {{trunc_ln2849_1_fu_407_p1}, {8'd0}};

assign trunc_ln2815_fu_800_p1 = bitcast_ln2815_fu_786_p1[22:0];

assign trunc_ln2849_1_fu_407_p1 = counter[8:0];

assign trunc_ln2849_fu_403_p1 = counter[10:0];

assign trunc_ln2885_1_fu_530_p1 = data_3_fu_517_p1[22:0];

assign trunc_ln2885_fu_489_p1 = data_2_fu_476_p1[22:0];

assign trunc_ln3417_fu_945_p1 = sdiv_ln3417_reg_1185[26:0];

assign trunc_ln3418_fu_972_p1 = sdiv_ln3418_reg_1190[23:0];

assign trunc_ln505_fu_847_p1 = data_fu_834_p1[51:0];

assign val_2_fu_706_p3 = ((tmp_12_reg_1110[0:0] == 1'b1) ? tmp_31_reg_1115 : tmp_32_reg_1120);

assign val_3_fu_763_p3 = ((tmp_14_reg_1131[0:0] == 1'b1) ? tmp_33_fu_743_p4 : tmp_34_fu_753_p4);

assign val_fu_1023_p3 = ((tmp_reg_1195[0:0] == 1'b1) ? tmp_15_reg_1222 : tmp_16_reg_1227);

assign x_ratio_fu_965_p2 = ($signed(sext_ln3417_fu_961_p1) + $signed(28'd1));

assign xs_exp_2_fu_479_p4 = {{data_2_fu_476_p1[30:23]}};

assign xs_exp_3_fu_520_p4 = {{data_3_fu_517_p1[30:23]}};

assign xs_exp_fu_837_p4 = {{data_fu_834_p1[62:52]}};

assign y_ratio_fu_988_p2 = (select_ln3418_fu_981_p3 + 24'd1);

assign zext_ln15_2_fu_582_p1 = mantissa_2_fu_572_p4;

assign zext_ln15_3_fu_720_p1 = mantissa_3_fu_711_p4;

assign zext_ln15_fu_861_p1 = mantissa_fu_851_p4;

assign zext_ln18_2_fu_626_p1 = $unsigned(sext_ln18_6_fu_622_p1);

assign zext_ln18_3_fu_727_p1 = $unsigned(sext_ln18_8_fu_724_p1);

assign zext_ln18_fu_905_p1 = $unsigned(sext_ln18_4_fu_901_p1);

assign zext_ln317_1_fu_670_p1 = xs_exp_3_fu_520_p4;

assign zext_ln317_fu_586_p1 = xs_exp_2_fu_479_p4;

assign zext_ln486_fu_865_p1 = xs_exp_fu_837_p4;

always @ (posedge ap_clk) begin
    add_ln2851_reg_1050[5:0] <= 6'b000000;
end

endmodule //detectFaces
