// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module detectFaces_detectFaces_Pipeline_imageScalerL1_imageScalerL1_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        y_ratio,
        result_16,
        IMG1_data_address0,
        IMG1_data_ce0,
        IMG1_data_we0,
        IMG1_data_d0,
        result_15,
        sext_ln3417_1,
        Data_address0,
        Data_ce0,
        Data_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [23:0] y_ratio;
input  [31:0] result_16;
output  [16:0] IMG1_data_address0;
output   IMG1_data_ce0;
output   IMG1_data_we0;
output  [7:0] IMG1_data_d0;
input  [31:0] result_15;
input  [27:0] sext_ln3417_1;
output  [16:0] Data_address0;
output   Data_ce0;
input  [7:0] Data_q0;

reg ap_idle;
reg IMG1_data_ce0;
reg IMG1_data_we0;
reg Data_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln3420_fu_160_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire  signed [31:0] sext_ln3417_1_cast_fu_138_p1;
reg  signed [31:0] sext_ln3417_1_cast_reg_409;
wire   [0:0] icmp_ln3421_fu_175_p2;
reg   [0:0] icmp_ln3421_reg_418;
wire   [8:0] select_ln3408_fu_181_p3;
reg   [8:0] select_ln3408_reg_423;
reg   [8:0] select_ln3408_reg_423_pp0_iter1_reg;
reg   [8:0] select_ln3408_reg_423_pp0_iter2_reg;
reg   [8:0] select_ln3408_reg_423_pp0_iter3_reg;
wire   [7:0] select_ln3420_fu_214_p3;
reg   [7:0] select_ln3420_reg_429;
reg   [7:0] select_ln3420_reg_429_pp0_iter2_reg;
reg   [7:0] select_ln3420_reg_429_pp0_iter3_reg;
wire   [31:0] zext_ln3421_fu_236_p1;
wire   [0:0] or_ln3423_fu_251_p2;
reg   [0:0] or_ln3423_reg_441;
reg   [0:0] or_ln3423_reg_441_pp0_iter2_reg;
reg   [0:0] or_ln3423_reg_441_pp0_iter3_reg;
reg   [0:0] or_ln3423_reg_441_pp0_iter4_reg;
reg   [7:0] tmp_25_reg_445;
wire   [16:0] add_ln3424_1_fu_302_p2;
reg   [16:0] add_ln3424_1_reg_451;
reg   [15:0] trunc_ln6_reg_456;
reg   [16:0] IMG1_data_addr_reg_461;
wire   [63:0] zext_ln3424_5_fu_355_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln3424_6_fu_368_p1;
reg   [8:0] j_2_fu_72;
wire   [8:0] add_ln3421_fu_189_p2;
wire    ap_loop_init;
reg   [8:0] ap_sig_allocacmp_j_2_load;
reg   [7:0] i_fu_76;
reg   [16:0] indvar_flatten_fu_80;
wire   [16:0] add_ln3420_1_fu_166_p2;
reg   [16:0] ap_sig_allocacmp_indvar_flatten_load;
wire   [8:0] grp_fu_134_p0;
wire  signed [27:0] grp_fu_134_p1;
wire   [7:0] add_ln3420_fu_208_p2;
wire   [31:0] zext_ln3420_fu_221_p1;
wire   [0:0] slt_fu_225_p2;
wire   [0:0] icmp_ln3423_fu_240_p2;
wire   [0:0] xor_ln3423_fu_245_p2;
wire   [0:0] rev_fu_230_p2;
wire   [7:0] empty_fu_265_p0;
wire   [23:0] empty_fu_265_p2;
wire   [15:0] tmp_26_fu_280_p3;
wire   [13:0] tmp_27_fu_291_p3;
wire   [16:0] zext_ln3424_2_fu_287_p1;
wire   [16:0] zext_ln3424_3_fu_298_p1;
wire   [31:0] grp_fu_134_p2;
wire   [15:0] tmp_s_fu_318_p3;
wire   [13:0] tmp_24_fu_329_p3;
wire   [16:0] zext_ln3424_fu_325_p1;
wire   [16:0] zext_ln3424_1_fu_336_p1;
wire   [16:0] add_ln3424_fu_340_p2;
wire   [16:0] zext_ln3424_4_fu_346_p1;
wire   [16:0] add_ln3424_2_fu_349_p2;
wire  signed [16:0] sext_ln3424_fu_360_p1;
wire   [16:0] add_ln3424_3_fu_363_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [23:0] empty_fu_265_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 j_2_fu_72 = 9'd0;
#0 i_fu_76 = 8'd0;
#0 indvar_flatten_fu_80 = 17'd0;
#0 ap_done_reg = 1'b0;
end

detectFaces_mul_9ns_28s_32_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 28 ),
    .dout_WIDTH( 32 ))
mul_9ns_28s_32_3_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_134_p0),
    .din1(grp_fu_134_p1),
    .ce(1'b1),
    .dout(grp_fu_134_p2)
);

detectFaces_mul_8ns_24s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mul_8ns_24s_24_1_1_U5(
    .din0(empty_fu_265_p0),
    .din1(y_ratio),
    .dout(empty_fu_265_p2)
);

detectFaces_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_76 <= 8'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            i_fu_76 <= select_ln3420_fu_214_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln3420_fu_160_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_80 <= add_ln3420_1_fu_166_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_80 <= 17'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln3420_fu_160_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_2_fu_72 <= add_ln3421_fu_189_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_2_fu_72 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        IMG1_data_addr_reg_461 <= zext_ln3424_5_fu_355_p1;
        add_ln3424_1_reg_451[16 : 6] <= add_ln3424_1_fu_302_p2[16 : 6];
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        or_ln3423_reg_441_pp0_iter2_reg <= or_ln3423_reg_441;
        or_ln3423_reg_441_pp0_iter3_reg <= or_ln3423_reg_441_pp0_iter2_reg;
        or_ln3423_reg_441_pp0_iter4_reg <= or_ln3423_reg_441_pp0_iter3_reg;
        select_ln3408_reg_423_pp0_iter2_reg <= select_ln3408_reg_423_pp0_iter1_reg;
        select_ln3408_reg_423_pp0_iter3_reg <= select_ln3408_reg_423_pp0_iter2_reg;
        select_ln3420_reg_429_pp0_iter2_reg <= select_ln3420_reg_429;
        select_ln3420_reg_429_pp0_iter3_reg <= select_ln3420_reg_429_pp0_iter2_reg;
        tmp_25_reg_445 <= {{empty_fu_265_p2[23:16]}};
        trunc_ln6_reg_456 <= {{grp_fu_134_p2[31:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln3421_reg_418 <= icmp_ln3421_fu_175_p2;
        or_ln3423_reg_441 <= or_ln3423_fu_251_p2;
        select_ln3408_reg_423 <= select_ln3408_fu_181_p3;
        select_ln3408_reg_423_pp0_iter1_reg <= select_ln3408_reg_423;
        select_ln3420_reg_429 <= select_ln3420_fu_214_p3;
        sext_ln3417_1_cast_reg_409 <= sext_ln3417_1_cast_fu_138_p1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        Data_ce0 = 1'b1;
    end else begin
        Data_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        IMG1_data_ce0 = 1'b1;
    end else begin
        IMG1_data_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (or_ln3423_reg_441_pp0_iter4_reg == 1'd0))) begin
        IMG1_data_we0 = 1'b1;
    end else begin
        IMG1_data_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln3420_fu_160_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten_load = 17'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_80;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j_2_load = 9'd0;
    end else begin
        ap_sig_allocacmp_j_2_load = j_2_fu_72;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Data_address0 = zext_ln3424_6_fu_368_p1;

assign IMG1_data_address0 = IMG1_data_addr_reg_461;

assign IMG1_data_d0 = Data_q0;

assign add_ln3420_1_fu_166_p2 = (ap_sig_allocacmp_indvar_flatten_load + 17'd1);

assign add_ln3420_fu_208_p2 = (i_fu_76 + 8'd1);

assign add_ln3421_fu_189_p2 = (select_ln3408_fu_181_p3 + 9'd1);

assign add_ln3424_1_fu_302_p2 = (zext_ln3424_2_fu_287_p1 + zext_ln3424_3_fu_298_p1);

assign add_ln3424_2_fu_349_p2 = (add_ln3424_fu_340_p2 + zext_ln3424_4_fu_346_p1);

assign add_ln3424_3_fu_363_p2 = ($signed(add_ln3424_1_reg_451) + $signed(sext_ln3424_fu_360_p1));

assign add_ln3424_fu_340_p2 = (zext_ln3424_fu_325_p1 + zext_ln3424_1_fu_336_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign empty_fu_265_p0 = empty_fu_265_p00;

assign empty_fu_265_p00 = select_ln3420_reg_429;

assign grp_fu_134_p0 = zext_ln3421_fu_236_p1;

assign grp_fu_134_p1 = sext_ln3417_1_cast_reg_409;

assign icmp_ln3420_fu_160_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 17'd76800) ? 1'b1 : 1'b0);

assign icmp_ln3421_fu_175_p2 = ((ap_sig_allocacmp_j_2_load == 9'd320) ? 1'b1 : 1'b0);

assign icmp_ln3423_fu_240_p2 = (($signed(zext_ln3421_fu_236_p1) < $signed(result_15)) ? 1'b1 : 1'b0);

assign or_ln3423_fu_251_p2 = (xor_ln3423_fu_245_p2 | rev_fu_230_p2);

assign rev_fu_230_p2 = (slt_fu_225_p2 ^ 1'd1);

assign select_ln3408_fu_181_p3 = ((icmp_ln3421_fu_175_p2[0:0] == 1'b1) ? 9'd0 : ap_sig_allocacmp_j_2_load);

assign select_ln3420_fu_214_p3 = ((icmp_ln3421_reg_418[0:0] == 1'b1) ? add_ln3420_fu_208_p2 : i_fu_76);

assign sext_ln3417_1_cast_fu_138_p1 = $signed(sext_ln3417_1);

assign sext_ln3424_fu_360_p1 = $signed(trunc_ln6_reg_456);

assign slt_fu_225_p2 = (($signed(zext_ln3420_fu_221_p1) < $signed(result_16)) ? 1'b1 : 1'b0);

assign tmp_24_fu_329_p3 = {{select_ln3420_reg_429_pp0_iter3_reg}, {6'd0}};

assign tmp_26_fu_280_p3 = {{tmp_25_reg_445}, {8'd0}};

assign tmp_27_fu_291_p3 = {{tmp_25_reg_445}, {6'd0}};

assign tmp_s_fu_318_p3 = {{select_ln3420_reg_429_pp0_iter3_reg}, {8'd0}};

assign xor_ln3423_fu_245_p2 = (icmp_ln3423_fu_240_p2 ^ 1'd1);

assign zext_ln3420_fu_221_p1 = select_ln3420_fu_214_p3;

assign zext_ln3421_fu_236_p1 = select_ln3408_reg_423;

assign zext_ln3424_1_fu_336_p1 = tmp_24_fu_329_p3;

assign zext_ln3424_2_fu_287_p1 = tmp_26_fu_280_p3;

assign zext_ln3424_3_fu_298_p1 = tmp_27_fu_291_p3;

assign zext_ln3424_4_fu_346_p1 = select_ln3408_reg_423_pp0_iter3_reg;

assign zext_ln3424_5_fu_355_p1 = add_ln3424_2_fu_349_p2;

assign zext_ln3424_6_fu_368_p1 = add_ln3424_3_fu_363_p2;

assign zext_ln3424_fu_325_p1 = tmp_s_fu_318_p3;

always @ (posedge ap_clk) begin
    add_ln3424_1_reg_451[5:0] <= 6'b000000;
end

endmodule //detectFaces_detectFaces_Pipeline_imageScalerL1_imageScalerL1_1
